name: GitHub Classroom Workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
          
      - name: Install R dependencies
        run: |
          R -e "install.packages(c('tidyverse', 'readxl'), repos='https://cran.rstudio.com/')"
          
      - name: Run tests
        uses: education/autograding@v1
